services:
  postgres:
    image: postgres:16
    container_name: bia_postgres
    restart: always
    environment:
      - POSTGRES_DB=bia_dwh
      - POSTGRES_USER=bia_dwh
      - POSTGRES_PASSWORD=bia_dwh
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    networks:
      - bia_net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:

networks:
  bia_net:
    external: true
